### ISSUE TITLE
The certificate is self-signed, and untrusted

### ISSUE THREAD

**Issue by vukitoso** [jbagg/QSslSocket-example#1]
Hello.
I generate certificates according to the instructions - http://www.infidigm.net/articles/qsslsocket_for_ssl_beginners/
Collected an example of both_auth. When connecting a client to the server, it gives an error:

> "The certificate is self-signed, and untrusted"
> Server disconnected

How I generated certificates:
```
openssl req -out blue_ca.pem -new -x509 -nodes 
mv privkey.pem blue_privkey.pem
openssl req -out red_ca.pem -new -x509 -nodes 
mv privkey.pem red_privkey.pem


echo '00'>blue_index.txt
echo '00'>red_index.txt

openssl genrsa -out blue_local.key 1024
openssl req -key blue_local.key -new -out blue_local.req 
openssl x509 -req -in blue_local.req -CA blue_ca.pem -CAkey blue_privkey.pem -CAserial blue_index.txt -out blue_local.pem

openssl genrsa -out red_local.key 1024
openssl req -key red_local.key -new -out red_local.req 
openssl x509 -req -in red_local.req -CA red_ca.pem -CAkey red_privkey.pem -CAserial red_index.txt -out red_local.pem
```

When generating the certificate, I press inter, except for the "Common Name", I enter 127.0.0.1 there

**Comment by jbagg** [comment]
Try entering 127.0.0.1 only for the red request.

Also try entering different info for each request and CA.  By hitting 
enter you are entering the "same" info.  I was lazy and was hitting 
enter and got an error (I think the same one) when I started.

**Comment by vukitoso** [comment]
Thx, Work :)

> Note: One gotcha I ran into is that the info entered into each certificate must be different from certificate to certificate or strange things happen.

I read this phrase, but for some reason everywhere I entered the same thing. Thanks.

**Comment by vukitoso** [comment]
I tried using only RED certificates: red_ca.pem, red_local.pem, red_local.key. And everything works just as well for me.
Why did you decide to use blue on the server and red on the client. Why separation?
Why didn’t you use only RED or BLUE?
